"""Compatibility facade for FEOS PC-SAFT helpers.

This module keeps the historical import path
`gnnepcsaft.pcsaft.pcsaft_feos` stable while the implementation lives in
smaller, logically separated modules under `gnnepcsaft.pcsaft.feos`.
"""

from .feos import (
    critical_points_feos,
    get_records,
    henry_constant_feos,
    is_stable_feos,
    mix_bp_at_fixed_pressure_feos,
    mix_den_feos,
    mix_dp_at_fixed_pressure_feos,
    mix_e_gibbs_energy,
    mix_gibbs_energy,
    mix_lle_diagram_feos,
    mix_lle_feos,
    mix_ln_activity_coefficient,
    mix_ln_fugacity_coefficient,
    mix_ln_fugacity_coefficient_pure,
    mix_r_gibbs_energy,
    mix_r_isobaric_heat_capacity_feos,
    mix_tp_flash_feos,
    mix_vle_diagram_feos,
    mix_vle_pxy_diagram_feos,
    mix_vlle_diagram_feos,
    mix_vp_feos,
    parameters_gc_pcsaft,
    pc_saft,
    pc_saft_mixture,
    phase_diagram_feos,
    pure_den_feos,
    pure_h_lv_feos,
    pure_s_lv_feos,
    pure_surface_tension_feos,
    pure_viscosity_feos,
    pure_vp_feos,
)

__all__ = [
    "pc_saft",
    "pc_saft_mixture",
    "get_records",
    "mix_gibbs_energy",
    "mix_ln_fugacity_coefficient_pure",
    "mix_ln_activity_coefficient",
    "mix_e_gibbs_energy",
    "mix_ln_fugacity_coefficient",
    "mix_r_gibbs_energy",
    "mix_den_feos",
    "pure_den_feos",
    "mix_vp_feos",
    "mix_bp_at_fixed_pressure_feos",
    "mix_dp_at_fixed_pressure_feos",
    "pure_vp_feos",
    "pure_h_lv_feos",
    "pure_s_lv_feos",
    "critical_points_feos",
    "pure_viscosity_feos",
    "phase_diagram_feos",
    "is_stable_feos",
    "mix_tp_flash_feos",
    "henry_constant_feos",
    "mix_lle_diagram_feos",
    "mix_lle_feos",
    "mix_vle_diagram_feos",
    "mix_vle_pxy_diagram_feos",
    "mix_vlle_diagram_feos",
    "mix_r_isobaric_heat_capacity_feos",
    "pure_surface_tension_feos",
    "parameters_gc_pcsaft",
]
