name: Pylint

on:
  push:
    branches:
      - dev
    paths:
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv pip install pylint
          uv pip install -r requirements-torch.txt
          uv pip install -r requirements.txt
      - name: Analysing the code with pylint
        run: |
          uv run pylint $(git ls-files '*.py') --rcfile=.pylintrc
